config/routes.rb
Pruebaanimales3::Application.routes.draw do



resources :zonas
################
  match 'add_nota_zonas', :to => 'zonas#add_nota#id'
  match 'editar_tareas', :to => 'zonas#editar_tareas#id'
  #repasar permisos
  match 'administracionzonas', :to => 'zonas#administracionzonas'



resources :chenils
##################
  match 'cheniles', :to => 'zonas#cheniles#id'  
  match 'add_nota_chenil', :to => 'chenils#add_nota#id'



resources :animals
##################
  match 'ordenado', :to => 'animals#ordenado#id'
  match 'add_nota_animales', :to => 'animals#add_nota#id'
  match 'animals/nuevo', :to => 'animals#new' 
  match 'mover', :to => 'animals#mover#id1#id2'
  #visual##
  match 'moverfin', :to => 'animals#moverfin#id1#id2'
  match 'zona_mover', :to => 'animals#zona_mover#id'
  match 'moveraMiZona', :to => 'animals#moveraMiZona#id'
  #########
#  get 'animales/pagina/:page_id', :to=> 'animals#index#id#id'
  match 'animals', :to=> 'animals#index#page_id#zona'
  match 'ordenado', :to=> 'animals#ordenado#page_id#id#id'
  #get 'ordenado/pagina/:page_id', :to=> 'animals#ordenado#id#id#id'
#  get 'users/page/:page_id', to: 'users#index', as: 'users_pagination'

    resources :especies
    ###################

    resources :relacion_animals
    ###########################
	match 'relaciones/:id', :to => 'animals#relaciones'
	match 'relacionesXanimal/:id', :to => 'animals#relacionesXanimal'



resources :personas
###################
  get "personas/new"

    resources :ocupacions
    #####################

    resources :sessions, :only => [:new, :create, :destroy]
    ####################
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'
	get "sessions/new"



resources :diarios
##################
  match 'add_informe', :to => 'diarios#add_informe#id'
  match 'diarios/show', :to => 'diarios#show#fecha#zona'
  match 'diarios_new', :to => 'diarios#new#fecha#zona'
  match 'edittareadia', :to => 'diarios#edittareadia#id'



resources :horarios
###################
  match 'vistahorario', :to => 'horarios#vistahorario'
  match 'asignar_turno', :to => 'horarios#asignar_turno#date#tarde#zona'
  match 'crearturnodatos', :to => 'horarios#crearturnodatos#fecha#zona#tarde#persona'
  match 'horarios', :to => 'horarios#index#zona'
  match 'horarios', :to => 'horarios#index#zona#month'
  match 'horarios_informeSemana', :to => 'horarios#informeSemana#fecha#zona'
  match 'horarios_informeAnteriores', :to =>'horarios#informeAnteriores'
  match 'horarios_unificacion', :to => 'horarios#unificacion'
  match 'horarios_unificacionturnos', :to =>'horarios#unificacionturnos'
  match 'editar_informeAnterior', :to => 'horarios#editarinformeAnterior#id'




####################
match '/home', :to => 'pages#home'
root :to => 'sessions#new'
####################



end

app/controllers/especies_controller.rb
class EspeciesController < ApplicationController


#####################################
  # Listado de especies existentes
  # new.animal ->
  # edit.animal -> 
  # -> new, edit, destroy
#####################################

  def index
    @especies = Especie.all
  end


#####################################
  # Crea especie nueva
  #  index ->
  #  -> index
#####################################

  def new
    @especie = Especie.new
  end


#####################################
  # Guarda especie nueva
  #   invoca función "new" para recoger datos
#####################################

  def create
    @especie = Especie.new(params[:especie])
    if @especie.save
       redirect_to (especies_path), :notice => "Especie creada correctamente."
    else
      render :action => 'new'
    end
  end


#####################################
  # Edita nombre especie existente
  # index ->
  # -> update
#####################################

  def edit
    @especie = Especie.find(params[:id])
  end


#####################################
  # Guarda cambios en el nombre de una especie
  # edit ->
  # -> index
#####################################

  def update
    @especie = Especie.find(params[:id])
    if @especie.update_attributes(params[:especie])
       redirect_to (especies_path), :notice => "Especie modificada correctamente."
    else
      render :action => 'edit'
    end
  end


#####################################
  # Elimina especie
  # index ->
  # -> index
#####################################

  def destroy
    @especie = Especie.find(params[:id])
    @especie.destroy
    redirect_to especies_url, :notice => "Especie eliminada correctamente."
  end

end

app/helpers/especies_helper.rb
module EspeciesHelper
end

app/views/especies/_form.html.erb
<!--#####################################
  # Llamado por edit, new
  # -> update
  # -> create
#######################################-->

<h1></h1>

<%= form_for @especie do |f| %>
  <% if @especie.errors.any? %>
    <div id="error_explanation">
      <% flash[:error] = "Especie nueva no pudo ser creada correctamente" %>

      <ul>
      <% @especie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


</br>
</br >

  <p>
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </p>

</br>
  <div class="actions">
    <%= f.submit "Guardar Especie" %>
  </div>

<% end %>

app/views/especies/edit.html.erb
<!--#####################################
  # Edita nombre especie existente
  # index ->
  # -> update
#####################################-->

<h1>Editar especie</h1>
<hr/>

<%= render 'form' %>

</br>
</br>

<nav class="links_bajo">
  <span style="float:right">  
     <%= link_to "Listado Animales", animals_path %> |
     <%= link_to "Listado Especies", especies_path %>
  </span>
</nav>

app/views/especies/index.html.erb
<!--#####################################
  # Listado de especies existentes
  # ANIMAL.new ->
  # ANIMAL.edit -> 
  # -> new, edit, destroy
#######################################-->

<h1>Especies</h1>


<% if current_persona.ocupacion_id == 1 %> 
   <nav class="botonera2">
	<%= link_to 'Crear especie nueva', new_especy_path, :class=>"boton2verde enlaceb" %>
        </p>
   </nav>
<% end %> 
</br>

<hr/>

<table>
  <tr>
    <th>Nombre</th>
  </tr>
  <% for especie in @especies %>
     
     <tr>
       <td><%= especie.nombre %></td>
       <td><%= link_to "Editar", edit_especy_path(especie) %></td>
       <td><%= link_to "Eliminar", especie, :confirm => '¿Esta seguro?', :method => :delete %></td>
     </tr>
  <% end %>
</table>


</br>
</br>


<nav class="links_bajo">
  <span style="float:right">  
      <p><%= link_to "Volver listado animales", animals_path %></p>
  </span>
</nav>

app/views/especies/new.html.erb
<!--#####################################
  # Crea especie nueva
  #  index ->
  #  -> index
#######################################-->

<h1>Nueva Especie</h1>
<hr/>


<%= render 'form' %>

</br>



<nav class="links_bajo">
  <span style="float:right">  
       <%= link_to "Especies", especies_path %> | <%= link_to "Animales", animals_path %>
  </span>
</nav>