config/routes.rb
Pruebaanimales3::Application.routes.draw do



resources :zonas
################
  match 'add_nota_zonas', :to => 'zonas#add_nota#id'
  match 'editar_tareas', :to => 'zonas#editar_tareas#id'
  #repasar permisos
  match 'administracionzonas', :to => 'zonas#administracionzonas'



resources :chenils
##################
  match 'cheniles', :to => 'zonas#cheniles#id'  
  match 'add_nota_chenil', :to => 'chenils#add_nota#id'



resources :animals
##################
  match 'ordenado', :to => 'animals#ordenado#id'
  match 'add_nota_animales', :to => 'animals#add_nota#id'
  match 'animals/nuevo', :to => 'animals#new' 
  match 'mover', :to => 'animals#mover#id1#id2'
  #visual##
  match 'moverfin', :to => 'animals#moverfin#id1#id2'
  match 'zona_mover', :to => 'animals#zona_mover#id'
  match 'moveraMiZona', :to => 'animals#moveraMiZona#id'
  #########
#  get 'animales/pagina/:page_id', :to=> 'animals#index#id#id'
  match 'animals', :to=> 'animals#index#page_id#zona'
  match 'ordenado', :to=> 'animals#ordenado#page_id#id#id'
  #get 'ordenado/pagina/:page_id', :to=> 'animals#ordenado#id#id#id'
#  get 'users/page/:page_id', to: 'users#index', as: 'users_pagination'

    resources :especies
    ###################

    resources :relacion_animals
    ###########################
	match 'relaciones/:id', :to => 'animals#relaciones'
	match 'relacionesXanimal/:id', :to => 'animals#relacionesXanimal'



resources :personas
###################
  get "personas/new"

    resources :ocupacions
    #####################

    resources :sessions, :only => [:new, :create, :destroy]
    ####################
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'
	get "sessions/new"



resources :diarios
##################
  match 'add_informe', :to => 'diarios#add_informe#id'
  match 'diarios/show', :to => 'diarios#show#fecha#zona'
  match 'diarios_new', :to => 'diarios#new#fecha#zona'
  match 'edittareadia', :to => 'diarios#edittareadia#id'



resources :horarios
###################
  match 'vistahorario', :to => 'horarios#vistahorario'
  match 'asignar_turno', :to => 'horarios#asignar_turno#date#tarde#zona'
  match 'crearturnodatos', :to => 'horarios#crearturnodatos#fecha#zona#tarde#persona'
  match 'horarios', :to => 'horarios#index#zona'
  match 'horarios', :to => 'horarios#index#zona#month'
  match 'horarios_informeSemana', :to => 'horarios#informeSemana#fecha#zona'
  match 'horarios_informeAnteriores', :to =>'horarios#informeAnteriores'
  match 'horarios_unificacion', :to => 'horarios#unificacion'
  match 'horarios_unificacionturnos', :to =>'horarios#unificacionturnos'
  match 'editar_informeAnterior', :to => 'horarios#editarinformeAnterior#id'




####################
match '/home', :to => 'pages#home'
root :to => 'sessions#new'
####################



end

app/models/animal.rb
# == Schema Information
#
# Table name: animals
#
#  id                :integer         not null, primary key
#  nombre            :string(255)
#  raza              :string(255)
#  sexo              :string(255)
#  fecha_entrada     :date
#  observaciones     :text
#  created_at        :datetime        not null
#  updated_at        :datetime        not null
#  foto_file_name    :string(255)
#  foto_content_type :string(255)
#  foto_file_size    :integer
#  foto_updated_at   :datetime
#  chenil_id         :integer
#

class Animal < ActiveRecord::Base
     attr_accessible :nombre, :raza, :sexo, :fecha_entrada, :observaciones, 
:chenil_id, :foto, :veterinario, :notas, :especie_id, :zona_id, 
:edad, :nuevoNA

  belongs_to :chenil, :foreign_key=>'chenil_id'  

  belongs_to :especie, :foreign_key=>'especie_id'

  belongs_to :zona, :foreign_key=>'zona_id'

   #relacion muchos_a_muchos consigo misma 
   has_many(:relacion_animals, :foreign_key => :animal1_id, :dependent => :destroy)

   has_many(:reverse_relacion_animals, :class_name => :RelacionAnimal, :foreign_key => :animal2_id, :dependent => :destroy)

   has_many :animals, :through => :relacion_animals, :source => :animal2_id


   # Restricciones datos
   validates :zona_id, :presence => true

   validates :chenil_id, :presence => true

   validates :nombre, 
    :presence => {:message => "no puede estar vacio"},
    :length => { :in => 2..30, :message => " ERROR, longitud entre 2 y 30 caracteres" }

   validates :raza, :length => { :maximum => 25, :message => " ERROR, maximo 25 caracteres" }


  # Paperclip
  has_attached_file :foto,
		:styles => {
                      :thumb => "100x100>",
                      :medium => "300x300"
                 }



#definiciones busquedas
def self.search1(search)
    if (search)
      find(:all, :conditions => ['nombre LIKE ?', "%#{search}%"])
    else
      find(:all, :order => "nombre asc")
    end
end

def self.search4(search)
    if (search)
      find(:all, :conditions => ['raza LIKE ?', "%#{search}%"])
    else
      find(:all, :order => "raza asc, nombre asc")
    end
end

def self.search5(search)
    if (search)
       find(:all, :conditions => ["zona_id = ?", "#{search}"], :order => "nombre asc")
    else
      find(:all, :order => "zona_id asc, nombre asc")
    end
end

def self.search6(search)
    if (search)
       find(:all, :conditions => ["especie_id = ?", "#{search}"])
    else
      find(:all, :order => "especie_id asc")
    end
end

def self.search7(search)
    if (search)
       find(:all, :conditions => ["sexo LIKE ?", "%#{search}%"], :order => "nombre asc")
    else
      find(:all, :order => "sexo asc, nombre asc")
    end
end


def animals
  @animales ||= find_animals
end


private

def find_animals
  Animal.find(:all, :conditions => conditions)
end

def name_conditions
  ["animals.nombre LIKE ?", "%#{nombre}%"] unless nombre.blank?
end


def category_conditions
  ["animals.chenil_id = ?", zona_id] unless zona_id.blank?
end

def conditions
  [conditions_clauses.join(' AND '), *conditions_options]
end

def conditions_clauses
  conditions_parts.map { |condition| condition.first }
end

def conditions_options
  conditions_parts.map { |condition| condition[1..-1] }.flatten
end

def conditions_parts
  private_methods(false).grep(/_conditions$/).map { |m| send(m) }.compact
end

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController


#before_filter :signed_in?, :except => [:index, :show]
#407 (personal) before_filter :coorect_user, :only => [:edit, :update]
before_filter :authenticate
before_filter :usuario_c_v, :only => [:destroy, :new, :edit, :relaciones]
# ----------------- relaciones ??????????


  Coordinador=1
  Voluntario=2
  Veterinario=3
  Limpiador=4



#####################################
  # Listado de animales existentes
  #   menu->
  #   ordenado->
  #   -> ordenado 
  #   -> "show" ficha
  #   -> "new"
#####################################

  def index


   #recoge paramatro zona
   if params[:zona]!=nil
     if params[:zona]=="todas"
         $zonaurl=nil
     else
         @zonaurl = params[:zona]
         $zonaurl = @zonaurl
     end
   end
   
   if !$zonaurl.nil?
     @zona = Zona.find($zonaurl)
   end
#------------------------------------------

   #si no hay parametros de busqueda
   if params[:search].nil? && params[:especie]==nil && params[:sexo]==nil
      $numero=1
   end
   $numero

   #guarda parametro search
   if !params[:search].nil?
      @searchurl= params[:search]
      @busquedaurl = "#{@searchurl}"
   end

   #guarda parametro nombre
   if !params[:nombre].nil?
      @nombreurl= params[:nombre]
      @busquedaurl= @nombreurl
   end


   case $numero
    when 1 , nil
     if $zonaurl.nil? #|| @busquedaurl.nil? #comprobar condiciones: no $zona ó no $busqueda
  	@animals = Animal.search1(@busquedaurl)
     else
        if @busquedaurl.nil?
	    @animals = Animal.find(:all, :conditions => ['zona_id = ?', $zonaurl])
        else
            @animals = Animal.find(:all, :conditions => ['nombre LIKE ? AND zona_id = ?', '%'+@busquedaurl+'%', $zonaurl])
        end
     end
     $numero=1
     @busqueda = "nombre"


    when 4
     if !params[:raza].nil?
       @nombreurl= params[:raza]
       @busquedaurl= @nombreurl
     end

     if $zonaurl.nil?
        @animals = Animal.find(:all, :conditions => ['raza LIKE ?', '%'+@busquedaurl+'%'], :order => "raza asc, nombre asc")
     else
        @animals = Animal.find(:all, :conditions => ['raza LIKE ? AND zona_id = ?', '%'+@busquedaurl+'%', $zonaurl], :order => "raza asc, nombre asc")
     end       
        $numero = 4
       @busqueda = "raza"


   when 6
     @busquedaurl=params[:especie]
     if $zonaurl.nil?
  	@animals = Animal.search6(params[:especie])
     else
        @animals = Animal.find(:all, :conditions => ["especie_id = ? AND zona_id = ?", @busquedaurl, $zonaurl], :order => "nombre asc")
     end
        $numero=6
        @busqueda = "especie"


   when 7
     @busquedaurl=params[:sexo]
     if $zonaurl.nil?
  	@animals = Animal.search7(params[:sexo])
     else
        @animals = Animal.find(:all, :conditions => ["sexo LIKE ? AND zona_id = ?", @busquedaurl, $zonaurl], :order => "nombre asc")
     end
     $numero=7
     @busqueda = "sexo"

  end

   @chenils = Chenil.all
   @zonas = Zona.all


########################################################3
# PAGINACIÓN animales: todos/busquedaxzonas

    if @busquedaurl.nil? || @busquedaurl.empty?

      # Número de animaless por página
      @animales_por_pagina = 20 
      # Número de paginas totales
      @pagina_count = (@animals.count/@animales_por_pagina)+1

      # actualiza parametro pagina
      @pagina = params[:page_id].to_i
      @pagina = 1 unless @pagina > 0
      @pagina = @pagina_count unless @pagina < @pagina_count
      # Primer registro que debemos sacar según la pagina
      @comienzo = (@pagina - 1) * @animales_por_pagina

      # Extrae de la busqueda realizada los animales pertenecientes a una página 
      @animales_en_busqueda = @animals.count
      if @animales_en_busqueda > @animales_por_pagina
         @masanimales = 1
      end
      @animals = @animals.slice(@comienzo, @animales_por_pagina)
      @count4 = @animals.count

    end

      @count4 = @animals.count
#############################################################


	

   respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @animals }
   end
  end


#####################################
  # Listado de animales existentes
  #  index->
  #  -> index
  #  -> "show" ficha
  #  -> "new"
#####################################

  def ordenado

   if params[:busqueda]!=nil
       @busqueda = params[:busqueda]
   else
       @busqueda = "Nombre"
   end  


   #recoge parametro "zona"
   if params[:zona]!=nil
     if params[:zona]=="todas"
         $zonaurl=nil
     else
         @zonaurl = params[:zona]
         $zonaurl = @zonaurl
     end
   end

   if !$zonaurl.nil?
     @zona = Zona.find($zonaurl)
   end


  
   #Recoge parametro "busqueda"
   case params[:busqueda]
    when "Nombre"
     if $zonaurl.nil?
  	@animals = Animal.search1(params[:search])
     else
        @animals = Animal.find(:all, :conditions => ["zona_id = ?", $zonaurl], :order => "nombre asc")
     end
     $numero = 1  
#     $zonaurl = @zonaurl

    when "F.entrada"       
     if $zonaurl.nil?
       @animals = Animal.find(:all, :order => "fecha_entrada DESC, nombre asc")
     else
       @animals = Animal.find(:all, :conditions => ["zona_id = ?", $zonaurl], :order => "fecha_entrada DESC, nombre asc")
     end
     $numero=2
#     $zonaurl = @zonaurl

    when "F.modificacion"
     if $zonaurl.nil?
       @animals = Animal.find(:all, :order => "updated_at DESC, nombre asc")
     else
       @animals = Animal.find(:all, :conditions => ["zona_id = ?", $zonaurl], :order => "updated_at DESC, nombre asc")
     end
       $numero=3

    when "Raza"
     if $zonaurl.nil?
  	@animals = Animal.search4(params[:search])
     else
        @animals = Animal.find(:all, :conditions => ["zona_id = ?", $zonaurl], :order => "raza asc, nombre asc")
     end
#        $zonaurl = @zonaurl
        $numero = 4

    when "Especie"
     if $zonaurl.nil?
  	@animals = Animal.search6(params[:search])
     else
        @animals = Animal.find(:all, :conditions => ["zona_id = ?", $zonaurl], :order => "especie_id asc, nombre asc")
     end
     $numero = 6     

    when "Sexo"
     if $zonaurl.nil?
  	@animals = Animal.search7(params[:search])
     else
        @animals = Animal.find(:all, :conditions => ["zona_id = ?", $zonaurl], :order => "sexo asc, nombre asc")
     end
        $numero = 7
   end


    @chenils = Chenil.all
    @zonas = Zona.all

########################################################3
# PAGINACIÓN

    # Número de animaless por página
    @animales_por_pagina = 20 
    @pagina = params[:page_id].to_i
    @pagina = 1 unless @pagina > 0
    # Primer registro que debemos sacar según la pagina
    @comienzo = (@pagina - 1) * @animales_por_pagina
    # Número de paginas totales
    @pagina_count = (Animal.all.count/@animales_por_pagina)+1

    # Controla si hay mas animales que los que caben en una pagina 
    @animales_en_busqueda = @animals.count
    if @animales_en_busqueda > @animales_por_pagina
       @masanimales = 1
    end
    # Extrae de la busqueda realizada los animales pertenecientes a una página 
    @animals = @animals.slice(@comienzo, @animales_por_pagina)
 

#############################################################

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @animals }
    end

  end



#####################################
  # Muestra la ficha de un animal
  #   index->
  #   ordenado->
  #   -> editar, mover, eliminar, relaciones
  #   -> añadir nota
#####################################

  def show
    @animal = Animal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @animal }
    end
  end



#####################################
  # Añade una nota a un animal 
  #  show->
#####################################

  def add_nota
    @animal = Animal.find(params[:id])
  end



#####################################
  # Mueve un animal (dentro de su zona) 
  #  (de mi zona a zona de libremovimiento) 
  #  show->
  #  -> moverzona
#####################################

  def mover

    @animal = Animal.find(params[:id2])
    @zona = Zona.find(params[:id1])


    #Controlar animal.zona = user.zona || animal.zona <- libremoviento
    # permisos mover????????????????????????????????????????????????????????????????????????????????
    if ((@animal.zona_id != current_persona.zona_id && @animal.zona.libremovimiento!=1) || (@zona.id != current_persona.zona_id && @zona.libremovimiento!=1))
	flash[:notice] = 'Acceso no permitido, animal o zona restringida para su perfil.'
	redirect_to :action=>"show", :id=>@animal.id

    else
	@chenil = @animal.chenil_id
	@chenils = Chenil.find(:all, :conditions => ["zona_id = ?", @zona.id], :order => "numero ASC")
        #?????????? porque no por zona???
	@animals = Animal.where("chenil_id in (?)", @chenils) 
	@relacion_animals = RelacionAnimal.find(:all, :conditions => ["animal1_id = ? OR animal2_id = ?", @animal.id, @animal.id])	

	respond_to do |format|
		format.html # index.html.erb
		format.json { render json: @animals }
	end
    end

  end



#####################################
  # Elige zona de libremoviento a la que mover animal 
  #  mover->
  #  ->mover
#####################################

  def zona_mover
    @animal = Animal.find(params[:id])
    @zonas = Zona.find(:all, :conditions => ["libremovimiento = ?", 1])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @animal }
    end
  end



#####################################
#??????????????????????????????????????????????????????????????
# no es necesaria, pero si la dejo: visual
# redirect animal, flash animal movido correctamente
#####################################
#####################################
  # Guarda los cambios en el movimiento del animal 
  #  mover->
  #  ->show ()redirect-------------------------------
#####################################

  def moverfin

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.erb
<!--#####################################
# Llamado por edit
# -> update
#######################################-->


<h1></h1>

<%= form_for @animal, :html => { :multipart =>true } do |f| %>
  <% if @animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% @animal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<hr/>

  <% if ((current_persona.ocupacion_id == 1 || current_persona.ocupacion_id == 3) && (@animal.zona_id==current_persona.zona_id)) %>

  <table class="tabla"> 

    <tr class="letragrande">
    <td>
      <div class="field">
        <%= f.label :nombre %><br />
        <%= f.text_field :nombre %>
      </div>
    </td>

    <td>
       <%= f.label :especie %><br />
       <select name="animal[especie_id]"> 
       <% @especies.each do |especie| %> 
          <option value="<%= especie.id %>" 
            <%= 'selected' if especie.id == @animal.especie_id %>>
            <%= especie.nombre %> 
          </option> 
       <% end %> 
       </select>
       <%= link_to " - Añadir Especie nueva", especies_path %>
    </td>
    </tr>

    <tr class="letragrande">
    <td>
      <div class="field">
        <%= f.label :raza %><br />
        <%= f.text_field :raza %>
      </div>
    </td>

    <td>
      <div class="field">
         <%= f.label :Sexo %><br />
         <%= f.select :sexo, ["neutro", "macho", "hembra"] %>
      </div>
    </td>
    </tr>

  </table>


  <div class="field">
    <%= f.label :Foto %><br />
    <%= f.file_field :foto %>
  </div>
  </br> 
  <hr/>

  <div class="field">
    <%= f.label :notas %><br />
    <%= f.text_area :notas %>
  </div>


  <div class="field">
    <%= f.label :observaciones %><br />
    <%= f.text_area :observaciones %>
  </div>

  <% end %>

  <% if current_persona.ocupacion_id==3 %>
    <div class="field">
      <%= f.label :veterinario %><br />
      <%= f.text_area :veterinario %>
    </div>
  <% end %>
 
  </br>
  <div class="actions">
    <%= f.submit "Guardar" %>
  </div>

<% end %>

app/views/animals/edit.html.erb
<!--#####################################
 # Edita información de un chenil
 #  show->
 #  -> _form
#######################################-->

<h1>Editar animal</h1>


<%= render 'form' %>

</br>

<nav class="links_bajo">
  <span style="float:right">  
     <%= link_to 'Ficha animal', @animal %> |
     <%= link_to 'Listado animales', animals_path %>
  </span>
</nav>

app/views/animals/new.html.erb
<!--#####################################
# Crea animal nuevo
#  index ->
#  -> show
######################################-->

<h1>Nuevo animal</h1>
<hr/>
</br>


<!--Controlar cheniles zona con caplibre>0---------------->
<!-- @chenils=Chenil.where("chenils.zona_id = ? AND caplibre > ?", @zona, 0) %--> 
<% if @chenils.empty?%>
    </br>
    <%= "-No hay cheniles con capacidad libre en su zona" %></br>
    <%= "-Cree un chenil nuevo con capacidad antes de crear un animal"%>
    </br>
    </br>
    </br>

<% else %>
  <%= form_for(@animal, :html => {:multipart=>true}) do |f| %>
    <% if @animal.errors.any? %>
      <div id="error_explanation">
        <% flash[:error] = "Animal nuevo no pudo ser creado correctamente" %>
        <ul>
        <% @animal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>



    <div class="field">
	<%= f.label :nombre %><br />
	<%= f.text_field :nombre %>
    </div>


    <%= f.label :epecie %><br />  
    <select name="animal[especie_id]"> 
     <% @especies.each do |especie| %> 
         <option value="<%= especie.id %>" 
           <%= 'selected' if especie.id == @animal.especie_id %>>
           <%= especie.nombre %> 
         </option> 
     <% end %> 
    </select>
    <%= link_to " - Añadir Especie nueva", especies_path %>
  

    <div class="field">
	<%= f.label :raza %><br />
	<%= f.text_field :raza %>
        <% @aux=:raza %>
    </div>


    <div class="field">
       <%= f.label :Sexo %><br />
       <%= f.select :sexo, ["neutro", "macho", "hembra"] %>
    </div>
 

    <div>
      <%= f.label :Chenil %><br />
      <select name="animal[chenil_id]"> 
      <% @chenils.each do |chenil| %> 
        <option value="<%= chenil.id %>" 
          <%= 'selected' if chenil.id == @animal.chenil_id %>>
          <%= chenil.numero %> 
        </option> 

        <% @animal.zona_id=chenil.zona_id %>	

      <% end %> 
      </select>

      <%= " - " %>
      <%= @zona.nombre %>
    </div>


    <div class="field">
	<%= f.label :Foto %><br/>
  	<%= f.file_field :foto %>
    </div> 
    </br>

    <div class="field">
	<%= f.label :Observaciones %><br/>
  	<%= f.text_area :observaciones %>
    </div> 
    </br>


    <div class="actions">
       <%= f.submit "Guardar nuevo" %>
    </div>
    </br>

  <% end %>

<%end%>

<nav class="links_bajo">
  <span style="float:right">  
	<%= link_to 'Atras', animals_path %>
  </span>
</nav>

app/views/animals/relacionesXanimal.html.erb
<!--#####################################
 # Muestra las relaciones existentes entre un animal y sus compañeros
 #  show->
 #  VISTA COMO EN MOVER X CHENILES??
#######################################-->

<h1>Relaciones <%= @animal.nombre %></h1>



<% if !current_persona.nil? && (current_persona.ocupacion_id == 1 || current_persona.ocupacion_id ==3) && @animal.zona_id==current_persona.zona_id %>

  <nav class="botonera2">
    <a href="/relaciones/<%=@animal.id%>" class="boton2verde enlaceb">Crear Nueva Relacion</a>
  </nav>
  </p>    

<% end %>

<hr/>

<center>
<table class="tabla">
  <tr>

    <th>Foto</th>
    <th>Nombre</th>
    <th>Zona</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tr>


    <% if @animal.foto_content_type.nil? %>
       <td><%= link_to image_tag('logo.png'), @animal %></td>
    <% else %>
       <td><%= link_to image_tag(@animal.foto.url(:thumb)), @animal %></td>
    <%end%>

    <td><%= @animal.nombre %></td>
    <td><%= @animal.chenil.zona.nombre %></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>
</center>
<hr/>

<center>
<table class="tabla">
  <tr>
    <th>Foto</th>
    <th>Nombre</th>
    <th>Zona animal</th>



    <th>Relacion</th>
<% if (current_persona.ocupacion_id == 1 || current_persona.ocupacion_id == 3) %>
    <th></th>
    <th></th>
<%end%>
  </tr>



 <% @relacionplus.each do |relacion_animal| %>

  <!--borrado relaciones sin algun animal-->
  <% if relacion_animal.animal.nil? || relacion_animal.animal2.nil? %>
	<% relacion_animal.destroy %>
  <% else %>

  <% if ( @animal.id == relacion_animal.animal2_id) %> 
 

	  <tr>
	   <td>
           <% if @animal.foto_content_type.nil? %>
           <!-- if relacion_animal.animal.foto_content_type.nil? %-->
              <%= link_to image_tag('logo.png'), relacion_animal.animal %>
           <% else %>
              <%= link_to image_tag(relacion_animal.animal.foto.url(:thumb)), relacion_animal.animal %>
           <%end%>
           </td>

	   <td><%= relacion_animal.animal.nombre %></td>
	   <td><%= relacion_animal.animal.chenil.zona.nombre %>


	   <td><%= relacion_animal.relacion %></td>
  
           <% if (current_persona.ocupacion_id == 1 || current_persona.ocupacion_id == 3) && (relacion_animal.animal.zona_id == current_persona.zona_id ||relacion_animal.animal2.zona_id == current_persona.zona_id)  %>
               <td><%= link_to 'Editar', edit_relacion_animal_path(relacion_animal) %></td>
	       <td><%= link_to 'Eliminar', relacion_animal, confirm: '¿Esta seguro?', method: :delete %></td>
	   <% else %>
	       <td></td>
	       <td></td>
	   <% end %>
	  </tr>

  <%end%>

  <% if @animal.id == relacion_animal.animal1_id %>
	  <tr>

           <td>
           <% if relacion_animal.animal2.foto_content_type.nil? %>
                  <%= link_to image_tag('logo.png'), relacion_animal.animal2 %></td>
           <% else %>
                  <%= link_to image_tag(relacion_animal.animal2.foto.url(:thumb)), relacion_animal.animal2 %>

           <%end%>
           </td>

	    <td><%= relacion_animal.animal2.nombre %></td>
	    <td><%= relacion_animal.animal2.chenil.zona.nombre %>


	    <td><%= relacion_animal.relacion %></td>

            <% if (current_persona.ocupacion_id == 1 || current_persona.ocupacion_id == 3) && (relacion_animal.animal2.zona_id==current_persona.zona_id || relacion_animal.animal.zona_id == current_persona.zona_id)  %>
	       <td><%= link_to 'Editar', edit_relacion_animal_path(relacion_animal) %></td>
	       <td><%= link_to 'Eliminar', relacion_animal, confirm: '¿Esta seguro?', method: :delete %></td>
            <%else%>
	       <td></td>
	       <td></td>
	    <%end%>
	  </tr>


  <%end%>
 <%end%>
 <% end %>
</table>
</center>


</br></br></br>
<nav class="links_bajo">
  <span style="float:right">  
	<%= link_to 'Ficha', @animal %> |
        <%= link_to 'Listado animales', animals_path %>
  </span>
</nav>

app/views/animals/zona_mover.html.erb
<!--#####################################
 # Elige zona de libremoviento a la que mover animal 
 #  mover->
 #  ->mover
########################################-->

<h1></h1>
</br>

<b>Listado de zonas de "libre movimiento"</b>
<hr/>
</br>

<% @cont=0 %>

<center>
<table class="tabla">

  <% @zonas.each do |zona| %>

    <% @cont=@cont+1 %>

    <% if @cont == 1 %>
     <tr class="letragrande">
     <td>
 	<%= link_to zona.nombre, :action=> "mover", :id1=> zona.id, :id2 => @animal.id %>
     </td>
    <% end %>
    <% if @cont == 2%>
     <td>
        <%= link_to zona.nombre, :action=> "mover", :id1=> zona.id, :id2 => @animal.id %>	
	<% @cont=0 %>
     </td>
     </tr>
  <% end %>


<%end%>
</table>
</center>

</br></br></br></br>
<nav class="links_bajo">
  <span style="float:right">  
	<%= link_to 'Atras', @animal %>
  </span>
</nav>