config/routes.rb
Pruebaanimales3::Application.routes.draw do



resources :zonas
################
  match 'add_nota_zonas', :to => 'zonas#add_nota#id'
  match 'editar_tareas', :to => 'zonas#editar_tareas#id'
  #repasar permisos
  match 'administracionzonas', :to => 'zonas#administracionzonas'



resources :chenils
##################
  match 'cheniles', :to => 'zonas#cheniles#id'  
  match 'add_nota_chenil', :to => 'chenils#add_nota#id'



resources :animals
##################
  match 'ordenado', :to => 'animals#ordenado#id'
  match 'add_nota_animales', :to => 'animals#add_nota#id'
  match 'animals/nuevo', :to => 'animals#new' 
  match 'mover', :to => 'animals#mover#id1#id2'
  #visual##
  match 'moverfin', :to => 'animals#moverfin#id1#id2'
  match 'zona_mover', :to => 'animals#zona_mover#id'
  match 'moveraMiZona', :to => 'animals#moveraMiZona#id'
  #########
#  get 'animales/pagina/:page_id', :to=> 'animals#index#id#id'
  match 'animals', :to=> 'animals#index#page_id#zona'
  match 'ordenado', :to=> 'animals#ordenado#page_id#id#id'
  #get 'ordenado/pagina/:page_id', :to=> 'animals#ordenado#id#id#id'
#  get 'users/page/:page_id', to: 'users#index', as: 'users_pagination'

    resources :especies
    ###################

    resources :relacion_animals
    ###########################
	match 'relaciones/:id', :to => 'animals#relaciones'
	match 'relacionesXanimal/:id', :to => 'animals#relacionesXanimal'



resources :personas
###################
  get "personas/new"

    resources :ocupacions
    #####################

    resources :sessions, :only => [:new, :create, :destroy]
    ####################
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'
	get "sessions/new"



resources :diarios
##################
  match 'add_informe', :to => 'diarios#add_informe#id'
  match 'diarios/show', :to => 'diarios#show#fecha#zona'
  match 'diarios_new', :to => 'diarios#new#fecha#zona'
  match 'edittareadia', :to => 'diarios#edittareadia#id'



resources :horarios
###################
  match 'vistahorario', :to => 'horarios#vistahorario'
  match 'asignar_turno', :to => 'horarios#asignar_turno#date#tarde#zona'
  match 'crearturnodatos', :to => 'horarios#crearturnodatos#fecha#zona#tarde#persona'
  match 'horarios', :to => 'horarios#index#zona'
  match 'horarios', :to => 'horarios#index#zona#month'
  match 'horarios_informeSemana', :to => 'horarios#informeSemana#fecha#zona'
  match 'horarios_informeAnteriores', :to =>'horarios#informeAnteriores'
  match 'horarios_unificacion', :to => 'horarios#unificacion'
  match 'horarios_unificacionturnos', :to =>'horarios#unificacionturnos'
  match 'editar_informeAnterior', :to => 'horarios#editarinformeAnterior#id'




####################
match '/home', :to => 'pages#home'
root :to => 'sessions#new'
####################



end

app/models/ocupacion.rb
# == Schema Information
#
# Table name: ocupacions
#
#  id         :integer         not null, primary key
#  nombre     :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Ocupacion < ActiveRecord::Base

        has_many :tareas
        has_many :tareadiaria
        has_many :personas

end

app/controllers/ocupacions_controller.rb
#
# cambiar a fijos
# - no crear, no index, no editar, quitar todo, dejar solo modelo
#
#

class OcupacionsController < ApplicationController
before_filter :authenticate
before_filter :usuario_coordinador, :only => [:destroy, :edit, :new]


 # GET /ocupacions
  # GET /ocupacions.json
  def index
    @ocupacions = Ocupacion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ocupacions }
    end
  end

  # GET /ocupacions/1
  # GET /ocupacions/1.json
  def show
    @ocupacion = Ocupacion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ocupacion }
    end
  end

  # GET /ocupacions/new
  # GET /ocupacions/new.json
  def new
    @ocupacion = Ocupacion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ocupacion }
    end
  end

  # GET /ocupacions/1/edit
  def edit
    @ocupacion = Ocupacion.find(params[:id])
  end

  # POST /ocupacions
  # POST /ocupacions.json
  def create
    @ocupacion = Ocupacion.new(params[:ocupacion])

    respond_to do |format|
      if @ocupacion.save
        format.html { redirect_to @ocupacion, notice: 'Ocupacion was successfully created.' }
        format.json { render json: @ocupacion, status: :created, location: @ocupacion }
      else
        format.html { render action: "new" }
        format.json { render json: @ocupacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ocupacions/1
  # PUT /ocupacions/1.json
  def update
    @ocupacion = Ocupacion.find(params[:id])

    respond_to do |format|
      if @ocupacion.update_attributes(params[:ocupacion])
        format.html { redirect_to @ocupacion, notice: 'Ocupacion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ocupacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ocupacions/1
  # DELETE /ocupacions/1.json
  def destroy
    @ocupacion = Ocupacion.find(params[:id])
    @ocupacion.destroy

    respond_to do |format|
      format.html { redirect_to ocupacions_url }
      format.json { head :no_content }
    end
  end

private
  
	def usuario_coordinador
	   deny_destroy unless current_persona.ocupacion_id==1 
	end

        def deny_destroy
    	   store_location
    	   redirect_to (ocupacions_path), :notice => "Necesitas permisos de coordinador para crear/editar/destruir una ocupacion."
  	end

end

app/helpers/ocupacions_helper.rb
module OcupacionsHelper
end

app/views/ocupacions/_form.html.erb
<%= form_for(@ocupacion) do |f| %>
  <% if @ocupacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ocupacion.errors.count, "error") %> prohibited this ocupacion from being saved:</h2>

      <ul>
      <% @ocupacion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ocupacions/edit.html.erb
<h1>Editing ocupacion</h1>

<%= render 'form' %>

<%= link_to 'Show', @ocupacion %> |
<%= link_to 'Back', ocupacions_path %>

app/views/ocupacions/index.html.erb
<h1>Listing ocupacions</h1>

<% if current_persona.ocupacion_id == 1 %>
    <%= link_to 'Nueva ocupacion', new_ocupacion_path %>
<% end %>

<table>
  <tr>
    <th>Nombre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ocupacions.each do |ocupacion| %>
  <tr>
    <td><%= ocupacion.nombre %></td>
    <td><%= link_to 'Show', ocupacion %></td>
<% if current_persona.ocupacion_id == 1 %>
    <td><%= link_to 'Edit', edit_ocupacion_path(ocupacion) %></td>
    <td><%= link_to 'Destroy', ocupacion, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
<% end %>
</table>

<br />

app/views/ocupacions/new.html.erb
<h1>New ocupacion</h1>

<%= render 'form' %>

<%= link_to 'Back', ocupacions_path %>

app/views/ocupacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @ocupacion.nombre %>
</p>


<%= link_to 'Edit', edit_ocupacion_path(@ocupacion) %> |
<%= link_to 'Back', ocupacions_path %>