config/routes.rb
Pruebaanimales3::Application.routes.draw do



resources :zonas
################
  match 'add_nota_zonas', :to => 'zonas#add_nota#id'
  match 'editar_tareas', :to => 'zonas#editar_tareas#id'
  #repasar permisos
  match 'administracionzonas', :to => 'zonas#administracionzonas'



resources :chenils
##################
  match 'cheniles', :to => 'zonas#cheniles#id'  
  match 'add_nota_chenil', :to => 'chenils#add_nota#id'



resources :animals
##################
  match 'ordenado', :to => 'animals#ordenado#id'
  match 'add_nota_animales', :to => 'animals#add_nota#id'
  match 'animals/nuevo', :to => 'animals#new' 
  match 'mover', :to => 'animals#mover#id1#id2'
  #visual##
  match 'moverfin', :to => 'animals#moverfin#id1#id2'
  match 'zona_mover', :to => 'animals#zona_mover#id'
  match 'moveraMiZona', :to => 'animals#moveraMiZona#id'
  #########
#  get 'animales/pagina/:page_id', :to=> 'animals#index#id#id'
  match 'animals', :to=> 'animals#index#page_id#zona'
  match 'ordenado', :to=> 'animals#ordenado#page_id#id#id'
  #get 'ordenado/pagina/:page_id', :to=> 'animals#ordenado#id#id#id'
#  get 'users/page/:page_id', to: 'users#index', as: 'users_pagination'

    resources :especies
    ###################

    resources :relacion_animals
    ###########################
	match 'relaciones/:id', :to => 'animals#relaciones'
	match 'relacionesXanimal/:id', :to => 'animals#relacionesXanimal'



resources :personas
###################
  get "personas/new"

    resources :ocupacions
    #####################

    resources :sessions, :only => [:new, :create, :destroy]
    ####################
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'
	get "sessions/new"



resources :diarios
##################
  match 'add_informe', :to => 'diarios#add_informe#id'
  match 'diarios/show', :to => 'diarios#show#fecha#zona'
  match 'diarios_new', :to => 'diarios#new#fecha#zona'
  match 'edittareadia', :to => 'diarios#edittareadia#id'



resources :horarios
###################
  match 'vistahorario', :to => 'horarios#vistahorario'
  match 'asignar_turno', :to => 'horarios#asignar_turno#date#tarde#zona'
  match 'crearturnodatos', :to => 'horarios#crearturnodatos#fecha#zona#tarde#persona'
  match 'horarios', :to => 'horarios#index#zona'
  match 'horarios', :to => 'horarios#index#zona#month'
  match 'horarios_informeSemana', :to => 'horarios#informeSemana#fecha#zona'
  match 'horarios_informeAnteriores', :to =>'horarios#informeAnteriores'
  match 'horarios_unificacion', :to => 'horarios#unificacion'
  match 'horarios_unificacionturnos', :to =>'horarios#unificacionturnos'
  match 'editar_informeAnterior', :to => 'horarios#editarinformeAnterior#id'




####################
match '/home', :to => 'pages#home'
root :to => 'sessions#new'
####################



end

app/models/chenil.rb
# == Schema Information
#
# Table name: chenils
#
#  id         :integer         not null, primary key
#  zona_id    :integer
#  ocupado    :integer
#  capacidad  :integer
#  caplibre   :integer
#  notas      :text
#  estado     :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  numero     :integer
#

class Chenil < ActiveRecord::Base

attr_accessible :numero, :ocupado, :capacidad, :caplibre, :zona_id, :notas, :estado, :nuevoNC, :Informacion


attr_accessible :numero

	belongs_to :zona, :foreign_key=>'zona_id'

	has_many :animals

#restricciones/validaciones
	validates :zona_id, :presence => true

	validates :numero, :presence => {:message => "no puede estar vacio"},
                  :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 100, :message => "valor debe estar entre 0 y 100" }

	validates :capacidad, :presence => {:message => "no puede estar vacio"},
                  :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 100, :message => "valor debe estar entre 0 y 100" }


end

app/controllers/chenils_controller.rb
class ChenilsController < ApplicationController
 
before_filter :authenticate
#, :except => [:index, :show]
before_filter :usuario_coordinador, :only => [:destroy, :new, :edit]


#######################################################
# Meter cheniles de zonas aqui!!!!
#####################################
# Utiliza funcion:cheniles, controlador:zona para mostrar listado de cheniles
# -> "show"
# -> "new"
#####################################
  def index
    redirect_to :controller=>'zonas', :action=>"cheniles"
  end



#####################################
# Muestra la ficha de un chenil
#   index-> ###############################################
#   -> añadir nota
#   -> editar chenil
#####################################

  def show
    @chenil = Chenil.find(params[:id])
    @animals= Animal.find(:all, :conditions =>["chenil_id = ?", @chenil.id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chenil }
    end
  end


#####################################
# Añade nota a un chenil 
#  show->
#####################################

  def add_nota
    @chenil = Chenil.find(params[:id])
  end



#####################################
# Edita información de un chenil
#  show->
#####################################

  def edit
    @chenil = Chenil.find(params[:id])
  end



#####################################
# Crea chenil nuevo
#   index->############################################
#####################################

  def new
    @chenil = Chenil.new
    @zonas = Zona.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chenil }
    end
  end


#####################################
# Guarda chenil nuevo
#   invoca función "new" para recoger datos
#####################################

  def create
    @chenil = Chenil.new(params[:chenil])
#    @chenil.ocupado = 0
    @chenil.zona_id=current_persona.zona_id
    @chenil.caplibre=@chenil.capacidad


    #controlar "no duplicado de numero de chenil" en la misma zona
    @chenilcontrol = Chenil.find(:all, :conditions => ["zona_id = ? AND numero = ?", @chenil.zona_id, @chenil.numero]).first

    if @chenilcontrol.nil?

      respond_to do |format|
        if @chenil.save
          format.html { redirect_to @chenil, notice: 'Creado chenil nuevo.' }
          format.json { render json: @chenil, status: :created, location: @chenil }
        else
          format.html { render action: "new" }
          format.json { render json: @chenil.errors, status: :unprocessable_entity }
        end
      end

    else
       flash[:alert] = "Chenil no pudo ser creado, ya exite un chenil con ese numero para su zona"
       render :action => :new
    end

  end



#####################################
# Guarda datos nuevos en un chenil
#  edit->
#  add_nota->
#####################################
#################################################QUITAR EDITOR EXTENDIDO

  def update

    @chenil = Chenil.find(params[:id])
    @capacidad = @chenil.capacidad
    @numero = @chenil.numero
    @nombre = current_persona.nombre #????
    @date= Date.today.to_s
    if @chenil.capacidad<0
       @chenil.capacidad=0
    end

    respond_to do |format|

      if @chenil.update_attributes(params[:chenil])

         #controlar "no duplicado de numero de chenil" en la misma zona
         @chenilcontrol = Chenil.find(:all, :conditions => ["zona_id = ? AND numero = ?", @chenil.zona_id, @chenil.numero]).second
         if !@chenilcontrol.nil?
              @chenil.numero = @numero
              @chenil.capacidad = @capacidad
              @chenil.save
              flash[:alert] = "Chenil no pudo ser modificado, ya exite un chenil con ese numero para su zona"
              format.html { redirect_to @chenil }
              format.json { head :no_content }
         else
             #control coherencia capacidad chenil y capacidad nula
             if @chenil.capacidad < @chenil.ocupado 
                 @chenil.capacidad=@chenil.ocupado
                 @chenil.caplibre=0
                 @chenil.save
                 flash[:alert] = "Incoherencia en la capacidades del chenil resuelta, la capacidad no puede ser menor al numero de animales alojados."
                 format.html { redirect_to @chenil }
                 format.json { head :no_content }
             else
                #Controles corrector = modificación correcta
                format.html { redirect_to @chenil, notice: 'Chenil modificado correctamente.' }
                format.json { head :no_content }
             end
         
         end

      #error al modificar entidad
      else
        format.html { render action: "edit" }
        format.json { render json: @chenil.errors, status: :unprocessable_entity }
      end


      #si se añadió nota nueva
      if !@chenil.nuevoNC.nil? && !@chenil.nuevoNC.empty?
	if @chenil.notas.nil? || @chenil.notas.empty? 
		@chenil.notas= @date+" / "+@nombre+":  "+@chenil.nuevoNC
		@chenil.nuevoNC=""
		@chenil.save  		  	
	else
        	@chenil.notas= @chenil.notas+"\n"+@date+" / "+@nombre+":  "+@chenil.nuevoNC
		@chenil.nuevoNC=""
		@chenil.save
	end
      end


   end
  end


#####################################
# Elimina chenil del sistema
#   show->
#####################################

  def destroy
    @chenil = Chenil.find(params[:id])
    if (@chenil.zona_id!=current_persona.zona_id || (current_persona.ocupacion_id!=1 && current_persona.ocupacion_id!=3))
       flash[:alert] = 'Acceso no permitido, Los cheniles solo pueden ser eliminados por Coordinadores y Veterinarios en sus modulos.'
       redirect_to :action=>"show", :id=> @chenil.id
    else
      @animals=Animal.find(:first, :conditions => ["chenil_id = ?", @chenil.id])
      if (!@animals.nil?)
         flash[:alert] = 'No puede eliminar un chenil con animales dentro, mueva o borre los animales antes de eliminar el chenil.'
         redirect_to :action=>"show", :id=> @chenil.id
      else
         @chenil.destroy

        respond_to do |format|
	  format.html { redirect_to :controller=>"zonas", :action=>"cheniles" }
          format.json { head :no_content }
        end
      end

    end
  end



###################################
# Asignación ocupaciones a permisos
###################################

private

	def usuario_coordinador
	   deny_destroy unless (current_persona.ocupacion_id==1 || current_persona.ocupacion_id==3)
	end

        def deny_destroy
    	   store_location
    	   redirect_to (zonas_path), :notice => "Necesitas permisos de coordinador/veterinario para dar de alta/baja un chenil."
  	end

end

app/helpers/chenils_helper.rb
module ChenilsHelper
end

app/views/chenils/_form.html.erb
<!--#####################################
# recoge datos para "new"
#  new->
#####################################-->


<h1></h1>
<hr/>

<%= form_for(@chenil) do |f| %>
  <% if @chenil.errors.any? %>
    <div id="error_explanation">
      <% flash[:error] = "Chenil no pudo ser creado correctamente" %>
      <!--h2>< pluralize(@chenil.errors.count, "error") %> este chenil no pudo ser guardado:</h2-->

      <ul>
      <% @chenil.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

</br>
</br>

  <div class="field">
    <%= f.label :"Numero chenil" %><br />
    <%= f.number_field :numero %>
  </div>

  <div class="field">
    <%= f.label :capacidad %><br />
    <%= f.number_field :capacidad %>
  </div>

</br>

  <div class="field">
    <%= f.label :notas %><br />
    <%= f.text_area :notas, :style => "width:100%" %>
  </div>

  <div class="field">
    <%= f.label :Informacion %><br />
    <%= f.text_area :Informacion %>
  </div>

  </br>
  <div class="actions">
    <%= f.submit "Guardar" %>
  </div>
<% end %>

app/views/chenils/add_nota.html.erb
<!--#####################################
# Añade una nota nueva
#   guarda fecha y nombre de usuario
#   show->
    #####################################-->

<h1>Añadir nota nueva</h1>
<hr/>
</br>

<p>
  <b>chenil:</b>
  <%= @chenil.numero %>
</p>

<p>
  <b>zona:</b>
  <%= @chenil.zona.nombre %>
</p>

</br>
<div class="roundB">
<ul>
<p>
  <b>Notas:</b>

  <%= simple_format h @chenil.notas %>
</p>
</ul>
</div>

<%= form_for(@chenil) do |f| %>
  <% if @chenil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chenil.errors.count, "error") %> prohibited this chenil from being saved:</h2>

      <ul>
      <% @chenil.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  </br> 
  <b>Nota nueva:</b>

  <div class="field">
    <%= f.text_area :nuevoNC %>
  </div>
  </br>

  <div class="actions">
    <%= f.submit "Añadir nota" %>
  </div>
<% end %>

</br>
<nav class="links_bajo">
  <span style="float:right">  
	<%= link_to 'Ficha', @chenil %> |
	<%= link_to 'Listado cheniles', :action=> "cheniles", :controller=> "zonas", :id=> @chenil.zona_id %> 
  </span>
</nav>

app/views/chenils/edit.html.erb
<!--#####################################
# Edita información de un chenil
#  show->
#####################################-->

<h1>Editar chenil</h1>
<hr/>


<%= form_for(@chenil) do |f| %>
  <% if @chenil.errors.any? %>
    <div id="error_explanation">
      <% flash[:error] = "Este chenil no pudo ser modificado." %>


      <ul>
      <% @chenil.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

</br>



<!------------------------------------------>

  <div class="field">
    <%= f.label :"Numero chenil" %><br />
    <%= f.number_field :numero %>
  </div>

  <div class="field">
    <%= f.label :capacidad %><br />
    <%= f.number_field :capacidad %>
  </div>
  </br>

<!------------------------------------------>



  <div class="field">
    <%= f.label :notas %><br />
    <%= f.text_area :notas %>
  </div>
  </br>

  <div class="field">
    <%= f.label :Informacion %><br />
    <%= f.text_area :Informacion %>
  </div>

  </br>
  <div class="actions">
    <%= f.submit "Guardar" %>
  </div>
<% end %>



</br>
<nav class="links_bajo">
  <span style="float:right">  
	<%= link_to 'Ficha', @chenil %> |
	<%= link_to 'Listado cheniles', :action=> "cheniles", :controller=> "zonas", :id=> @chenil.zona_id %> 
  </span>
</nav>

app/views/chenils/new.html.erb
<!--#####################################
# Crea chenil nuevo
#   index->############################################
#   -> _form
#####################################-->


<h1>chenil nuevo</h1>

<%= render 'form' %>


</br>
<nav class="links_bajo">
  <span style="float:right">  
	<%= link_to "Atras", {:controller=> "zonas", :action=>"cheniles"} %>
  </span>
</nav>

app/views/chenils/show.html.erb
<!--#####################################
# Muestra la ficha de un chenil
#   index->  zona.cheniles-> ###############################################
#   -> añadir nota
#   -> editar chenil
#####################################-->


<h1>Ficha chenil</h1>


<% if ((current_persona.ocupacion_id == 1 || current_persona.ocupacion_id == 3) && current_persona.zona_id == @chenil.zona_id) %> 

     <nav class="botonera2">
	<a class="boton2verde enlaceb"<%= link_to 'Editar', edit_chenil_path(@chenil) %></a>
	<a class="boton2verde enlaceb"<%= link_to 'Eliminar', @chenil, confirm: 'Esta seguro de eliminar este chenil?', method: :delete %></a>
     </nav>

<% end %>
<hr/>
</br>

<p>
  <b>Chenil nº:</b>
  <%= @chenil.numero %>
</p>

<p>
  <b>Zona:</b>
  <%= @chenil.zona.nombre %>
</p>


<p>
  <b>Capacidad:</b>
  <%= @chenil.capacidad %>

  <%= "/" %>

  <b>Espacio:</b>
  <%= @chenil.caplibre %>
</p>


<hr/>
<table class="tabla">
<tr>
 <% @contadoraux=0 %>
 <% @animals.each do |animal| %>
	<% if animal.chenil_id == @chenil.id %>	
              <% if @contadoraux>5 %>
                   <% @contadoraux=0 %>
                   <tr class="modo1">
              <% end %>
              <td>
	      <% if animal.foto_content_type.nil? %>
   		 <center><%= link_to image_tag('logo.png'), animal %>
                 </br>
		 <%= link_to animal.nombre.from(0).to(18), animal %></center>
   	      <% else %>
    		 <center><%= link_to image_tag(animal.foto.url(:thumb)), animal %>
                 </br>
		 <%= link_to animal.nombre.from(0).to(18), animal %></center>
  	      <%end%>
	      </td>
              <% @contadoraux = @contadoraux+1 %>
        <% end %>
 <%end%>
</tr>
</table>
<hr/>


<p>
  <nav class="botonera2">

     <%= link_to 'añadir nota nueva', {:action => "add_nota", :id=> @chenil.id}, :class=>"boton2der" %>
  </nav>
</p>
</br>

<div class="roundB">
<p>
  <b>Notas:</b>     
    </br>
      <%= simple_format h @chenil.notas %>
</p>
</div>
</br></br>


<div class="roundB">
<p>
  <b>Informacion:</b>
    </br>
      <%= simple_format h @chenil.Informacion %>
</p>
</div>
</br></br></br>

<nav class="links_bajo">
  <span style="float:right">  
     <%= link_to 'Listado cheniles', :action=> "cheniles", :controller=> "zonas", :id=> @chenil.zona_id %>
  </span>
</nav>